/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.Comparator;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author javiershaka
 */
public class formSelectCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form formAgregarCliente
     */
    DefaultComboBoxModel _cbox;
    public formSelectCliente() {
        initComponents();
        jComboBox2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Clientes registrados");

        jLabel3.setText("Ver por");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nombre" }));
        jComboBox1.setToolTipText("");
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        jComboBox1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboBox1FocusGained(evt);
            }
        });

        jButton1.setText("Agregar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Detalles");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(38, 38, 38)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        jComboBox2.setVisible(true);
        _cbox = (DefaultComboBoxModel) jComboBox2.getModel();
        try {
            _cbox.removeAllElements();
            int Eleccion = jComboBox1.getSelectedIndex();
            if(Eleccion == 0){
                formCliente._clientesLista.sort(Comparator.comparing(modelo.Clientes::getID));
                for(modelo.Clientes _client : formCliente._clientesLista){
                    
                    _cbox.addElement(_client.getID());
                }
        
                
            }
            if(Eleccion == 1){
                formCliente._clientesLista.sort(Comparator.comparing(modelo.Clientes::getNombre));
                for(modelo.Clientes _client : formCliente._clientesLista){
                    _cbox.addElement(_client.getNombre());
                }
            }
           formSelectCelular.cbProductos.setModel(_cbox);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jComboBox1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboBox1FocusGained
        // TODO add your handling code here:
        jComboBox2.setVisible(true);
        _cbox = (DefaultComboBoxModel) jComboBox2.getModel();
        try {
            _cbox.removeAllElements();
            int Eleccion = jComboBox1.getSelectedIndex();
            if(Eleccion == 0){
                formCliente._clientesLista.sort(Comparator.comparing(modelo.Clientes::getID));
                for(modelo.Clientes _client : formCliente._clientesLista){
                    
                    _cbox.addElement(_client.getID());
                }
            }
            if(Eleccion == 1){
                formCliente._clientesLista.sort(Comparator.comparing(modelo.Clientes::getNombre));
                for(modelo.Clientes _client : formCliente._clientesLista){
                    _cbox.addElement(_client.getNombre());
                }
            }
           formSelectCelular.cbProductos.setModel(_cbox);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jComboBox1FocusGained

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        formVerificacionClientes _verificar = new formVerificacionClientes();
        formVentaCelulares.dskEscritorio.add(_verificar);
        int x = (int) (formVentaCelulares.dskEscritorio.getWidth() / 2) - (int) (_verificar.getWidth() / 2);
        int y = (int) (formVentaCelulares.dskEscritorio.getHeight() / 2) - (int) (_verificar.getHeight() / 2);

        _verificar.setLocation(x, y);
        _verificar.setVisible(true);
        for(int i =0; i < formCliente._clientesLista.size(); i++){
            if(formCliente._clientesLista.get(i).getNombre().equals(jComboBox2.getSelectedItem()+"")|| formCliente._clientesLista.get(i).getID().equals(jComboBox2.getSelectedItem()+"")){
                formVerificacionClientes.jTextField1.setText(formCliente._clientesLista.get(i).getID());
                formVerificacionClientes.jTextField2.setText(formCliente._clientesLista.get(i).getNombre());
                formVerificacionClientes.jTextField3.setText(formCliente._clientesLista.get(i).getDomicilio());
                formVerificacionClientes.jTextField4.setText(formCliente._clientesLista.get(i).getRFC());
                formVerificacionClientes.jTextField5.setText(formCliente._clientesLista.get(i).getTelefono());
                formVerificacionClientes.jTextField6.setText(formCliente._clientesLista.get(i).getCorreoElectronico());
                
                break;
            }
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        for(int i =0; i < formCliente._clientesLista.size(); i++){
            if(formCliente._clientesLista.get(i).getNombre().equals(jComboBox2.getSelectedItem()+"")|| formCliente._clientesLista.get(i).getID().equals(jComboBox2.getSelectedItem()+"")){
                formVenta.txtxID.setText(formCliente._clientesLista.get(i).getID());
                formVenta.txtNombre.setText(formCliente._clientesLista.get(i).getNombre());
                hide();
                break;
            }
        }
            
            
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        hide();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    public static javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
