// javiershaka
package Vistas;
import javax.swing.table.DefaultTableModel;
import modelo.Celulares;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
/**
 *
 * @author javiershaka
 */

public class formCelular extends javax.swing.JInternalFrame {
    
    Celulares _Celu = new Celulares();;
    
    
    DefaultComboBoxModel _cbProducto;
    public static List<Celulares> _listaCelular = new ArrayList<Celulares>();
    public formCelular() {
        initComponents();
        _listaCelular.add(new Celulares("16592", "Nokia asha 311", 450, 16, "Telcel"));
        _listaCelular.add(new Celulares("3278", "Samsung Galaxy S2", 16500, 32, "Telcel"));
        _listaCelular.add(new Celulares("77564", "LG 350", 7300, 20, "Movistar"));
        _listaCelular.add(new Celulares("56211", "Motorola 80S VIP ", 11700, 31, "AT&T"));
        _listaCelular.add(new Celulares("75987", "Iphone 7 plus", 18000, 8, "Apple"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtClasificacion = new javax.swing.JTextField();
        ftxtID = new javax.swing.JFormattedTextField();
        ftxtPrecio = new javax.swing.JFormattedTextField();
        ftxtStock = new javax.swing.JFormattedTextField();
        jButton2 = new javax.swing.JButton();

        setTitle("Datos del celular");

        jLabel1.setText("ID");

        jLabel2.setText("Nombre");

        jLabel3.setText("precio");

        jLabel4.setText("Stock");

        jButton1.setText("Guardad Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Compañia");

        ftxtID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0"))));

        ftxtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        ftxtStock.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ftxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(ftxtID)
                            .addComponent(ftxtPrecio)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ftxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ftxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ftxtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel _tablaProductos = (DefaultTableModel) Vistas.formListaCelulares.jTable1.getModel();
        boolean Identicos = false;
        if(txtClasificacion.getText().isEmpty() || txtNombre.getText().isEmpty() || ftxtID.getText().isEmpty() || ftxtPrecio.getText().isEmpty() || ftxtStock.getText().isEmpty() ){
            JOptionPane.showMessageDialog(null,"Favor de llenar todos los campos", "Mensae", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            
            
            if(!_listaCelular.isEmpty()){
                for(int i = 0; i < _listaCelular.size();i++){
                    
                    if(!(_listaCelular.get(i).getID().equals(ftxtID.getText()) || _listaCelular.get(i).getNombreProducto().toUpperCase().equals(txtNombre.getText().toUpperCase()))){
                        Identicos = true;   //use una variable booleana por va el ciclo recorriendo del 0 ansta que se acabe el agreglo pero si agregas uno y el primero es diferente que el segunto lo agrega pero al final te sale que no hay repetidos
                    
                    }
                    
                    else{
                    JOptionPane.showMessageDialog(null, "Ya hay un cliente con el mismo ID o nombre", "Aviso", JOptionPane.PLAIN_MESSAGE);
                        Identicos = false;
                    break;
                
                    }
                    
                
                }
                if(Identicos == true){
                        
                        
                        _listaCelular.add(new Celulares(ftxtID.getText(), txtNombre.getText(), Double.parseDouble(ftxtPrecio.getText()), Integer.parseInt(ftxtStock.getText()), txtClasificacion.getText()));
                        _tablaProductos.addRow(new Object[]{ftxtID.getText(),txtNombre.getText(),ftxtPrecio.getText(),ftxtStock.getText(),txtClasificacion.getText()});
                        Vistas.formListaCelulares.jTable1.setModel(_tablaProductos);
                        JOptionPane.showMessageDialog(null, "Se a agregado un nuevo producto","Aviso"  , JOptionPane.INFORMATION_MESSAGE);
                        hide();
                        txtNombre.setText("");
                        txtClasificacion.setText("");
                        ftxtID.setText("");
                        ftxtPrecio.setText("");
                        ftxtStock.setText("");
                        Identicos = false;
                      
                        
                    }
            
            }
            
            if(_listaCelular.isEmpty()){
                
                
                _listaCelular.add(new Celulares(ftxtID.getText(), txtNombre.getText(), Double.parseDouble(ftxtPrecio.getText()), Integer.parseInt(ftxtStock.getText()), txtClasificacion.getText()));
                _tablaProductos.addRow(new Object[]{ftxtID.getText(),txtNombre.getText(),ftxtPrecio.getText(),ftxtStock.getText(),txtClasificacion.getText()});
                Vistas.formListaCelulares.jTable1.setModel(_tablaProductos);
                JOptionPane.showMessageDialog(null, "Se a agregado un nuevo producto","Aviso"  , JOptionPane.INFORMATION_MESSAGE);
                hide();
                txtNombre.setText("");
                txtClasificacion.setText("");
                ftxtID.setText("");
                ftxtPrecio.setText("");
                ftxtStock.setText("");
            }
            //
            
            
        }
        System.out.println(""+_listaCelular.size());
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        hide();
        txtNombre.setText("");
        txtClasificacion.setText("");
        ftxtID.setText("");
        ftxtPrecio.setText("");
        ftxtStock.setText("");
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField ftxtID;
    private javax.swing.JFormattedTextField ftxtPrecio;
    private javax.swing.JFormattedTextField ftxtStock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtClasificacion;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
